'use client'
import { useState } from 'react'
import { useSession, signIn, signOut } from 'next-auth/react'
import { useQuery, useQueryClient, useMutation } from '@tanstack/react-query'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Badge } from '@/components/ui/badge'
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter } from '@/components/ui/dialog'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select'
import { Textarea } from '@/components/ui/textarea'
import { Loader2, LogIn, LogOut, Users, Building2, DollarSign, Briefcase, CalendarDays, FileText, Settings as SettingsIcon, HardHat, ShoppingCart, BarChart3, UserCircle, Calculator, Plus, Search, Trash2, Edit, X, Download, TrendingUp, TrendingDown, Clock, Shield, Banknote, BookOpen, Receipt, CheckCircle, XCircle, Moon, Sun, Bell } from 'lucide-react'
import { formatCurrency, cn } from '@/lib/utils'
import { findNavigation } from '@/ai/tools/find-navigation'
import { OfflineIndicator, SyncStatusProvider } from '@/context/sync-context'
import SystemExpertChatWidget from '@/components/ai/chat-widget'
import { GratuityCalculatorView } from '@/components/hr/gratuity-calculator-view'
import { LeaveRequestForm } from '@/components/hr/leave-request-form'
import { ContractClausesForm } from '@/components/clients/contract-clauses-form'
import { useTheme } from 'next-themes'

type Module = 'dashboard' | 'clients' | 'hr' | 'accounting' | 'contracts' | 'projects' | 'appointments' | 'reports' | 'construction' | 'purchasing' | 'warehouse' | 'settings'
const KWD = (n: number) => formatCurrency(n)

export default function Home() {
  const { data: session, status } = useSession()
  const [email, setEmail] = useState('admin@nova-erp.com')
  const [password, setPassword] = useState('admin123')
  const [loading, setLoading] = useState(false)
  const [activeModule, setActiveModule] = useState<Module>('dashboard')
  const [searchQuery, setSearchQuery] = useState('')
  const [searchResults, setSearchResults] = useState<any[] | null>(null)
  const { theme, setTheme } = useTheme()

  if (status === 'loading') return <div className="flex items-center justify-center min-h-screen"><Loader2 className="h-8 w-8 animate-spin text-[#F5820D]" /></div>
  if (!session) return (
    <div className="min-h-screen flex items-center justify-center bg-gradient-to-br from-orange-50 to-amber-50 p-4" dir="rtl">
      <Card className="w-full max-w-md rounded-3xl border-none shadow-2xl overflow-hidden">
        <CardHeader className="bg-gradient-to-br from-[#F5820D] to-[#FF8F00] p-8 text-center"><div className="w-20 h-20 bg-white/20 rounded-3xl mx-auto mb-4 flex items-center justify-center"><Building2 className="h-10 w-10 text-white" /></div><h1 className="text-3xl font-black text-white">Nova ERP</h1><p className="text-white/80 text-sm mt-1">نظام إدارة موارد المؤسسات للسوق الكويتي</p></CardHeader>
        <CardContent className="p-8 space-y-4">
          <div className="space-y-2"><Label className="font-bold text-gray-700">البريد الإلكتروني</Label><Input value={email} onChange={e => setEmail(e.target.value)} className="h-12 rounded-xl border-2" /></div>
          <div className="space-y-2"><Label className="font-bold text-gray-700">كلمة المرور</Label><Input type="password" value={password} onChange={e => setPassword(e.target.value)} className="h-12 rounded-xl border-2" /></div>
          <Button onClick={async () => { setLoading(true); const r = await signIn('credentials', { email, password, redirect: false }); if (r?.error) { setLoading(false); alert('فشل الدخول') } else window.location.reload() }} disabled={loading} className="w-full h-12 rounded-xl font-black text-lg gap-2 bg-[#F5820D] hover:bg-[#C45600]">{loading ? <Loader2 className="h-5 w-5 animate-spin" /> : <LogIn className="h-5 w-5" />} دخول</Button>
          <p className="text-center text-xs text-muted-foreground">تجريبي: admin@nova-erp.com / admin123</p>
        </CardContent>
      </Card>
    </div>
  )

  const handleSearch = (q: string) => { setSearchQuery(q); if (q.trim().length >= 2) { const r = findNavigation(q); setSearchResults(r ? [r] : []) } else setSearchResults(null) }
  const navSections = [
    { title: 'العمليات', items: [{ id: 'clients' as Module, labelAr: 'العملاء', icon: Users, color: 'text-blue-600' }, { id: 'projects' as Module, labelAr: 'المشاريع', icon: Building2, color: 'text-purple-600' }, { id: 'contracts' as Module, labelAr: 'العقود', icon: FileText, color: 'text-orange-600' }, { id: 'appointments' as Module, labelAr: 'المواعيد', icon: CalendarDays, color: 'text-cyan-600' }] },
    { title: 'المالية', items: [{ id: 'accounting' as Module, labelAr: 'المحاسبة', icon: Calculator, color: 'text-emerald-600' }, { id: 'reports' as Module, labelAr: 'التقارير', icon: BarChart3, color: 'text-indigo-600' }] },
    { title: 'الموارد', items: [{ id: 'hr' as Module, labelAr: 'الموارد البشرية', icon: UserCircle, color: 'text-sky-600' }, { id: 'construction' as Module, labelAr: 'المقاولات', icon: HardHat, color: 'text-amber-600' }, { id: 'purchasing' as Module, labelAr: 'المشتريات', icon: ShoppingCart, color: 'text-rose-600' }, { id: 'warehouse' as Module, labelAr: 'المخازن', icon: ShoppingCart, color: 'text-teal-600' }] },
    { title: 'النظام', items: [{ id: 'settings' as Module, labelAr: 'الإعدادات', icon: SettingsIcon, color: 'text-gray-600' }] },
  ]

  return (
    <div className="min-h-screen flex bg-stone-50 dark:bg-stone-900" dir="rtl">
      <aside className="w-64 bg-white dark:bg-stone-800 border-l border-stone-200 dark:border-stone-700 flex flex-col shrink-0">
        <div className="p-4 border-b dark:border-stone-700"><div className="flex items-center gap-3"><div className="w-10 h-10 bg-gradient-to-br from-[#F5820D] to-[#FF8F00] rounded-xl flex items-center justify-center"><Building2 className="h-5 w-5 text-white" /></div><div><h1 className="font-black text-sm dark:text-white">Nova ERP</h1><p className="text-[10px] text-muted-foreground">v1.0 — Prisma</p></div></div></div>
        <nav className="flex-1 overflow-y-auto p-2 space-y-4">
          <button onClick={() => setActiveModule('dashboard')} className={cn('w-full flex items-center gap-3 px-3 py-2.5 rounded-xl text-sm font-bold transition-all', activeModule === 'dashboard' ? 'bg-[#F5820D] text-white' : 'text-stone-600 dark:text-stone-300 hover:bg-stone-100 dark:hover:bg-stone-700')}><BarChart3 className="h-4 w-4" /> لوحة التحكم</button>
          {navSections.map(s => (<div key={s.title}><p className="text-[10px] font-black text-stone-400 uppercase tracking-wider px-3 mb-1">{s.title}</p>{s.items.map(i => { const Icon = i.icon; return <button key={i.id} onClick={() => setActiveModule(i.id)} className={cn('w-full flex items-center gap-3 px-3 py-2 rounded-xl text-sm font-medium transition-all', activeModule === i.id ? 'bg-orange-50 text-[#F5820D]' : 'text-stone-600 dark:text-stone-300 hover:bg-stone-100 dark:hover:bg-stone-700')}><Icon className={cn('h-4 w-4', activeModule === i.id ? 'text-[#F5820D]' : i.color)} /> {i.labelAr}</button> })}</div>))}
        </nav>
        <div className="p-3 border-t dark:border-stone-700">
          <div className="flex items-center gap-2 mb-2"><div className="w-8 h-8 bg-stone-200 dark:bg-stone-600 rounded-full flex items-center justify-center text-xs font-bold dark:text-white">{(session.user as any)?.name?.charAt(0) || 'A'}</div><div className="flex-1 min-w-0"><p className="text-xs font-bold truncate dark:text-white">{(session.user as any)?.name || 'Admin'}</p><p className="text-[10px] text-muted-foreground">{(session.user as any)?.role || 'admin'}</p></div></div>
          <div className="flex gap-1"><Button variant="ghost" size="sm" onClick={() => setTheme(theme === 'dark' ? 'light' : 'dark')} className="flex-1 text-xs gap-1 text-stone-500">{theme === 'dark' ? <Sun className="h-3 w-3" /> : <Moon className="h-3 w-3" />}</Button><Button variant="ghost" size="sm" onClick={() => signOut()} className="flex-1 text-xs gap-1 text-stone-500"><LogOut className="h-3 w-3" /> خروج</Button></div>
        </div>
      </aside>
      <main className="flex-1 overflow-auto">
        <div className="sticky top-0 z-30 bg-white/80 dark:bg-stone-800/80 backdrop-blur-sm border-b dark:border-stone-700 px-6 py-3 flex items-center gap-4">
          <div className="relative flex-1 max-w-md"><Search className="absolute right-3 top-1/2 -translate-y-1/2 h-4 w-4 text-stone-400" /><Input value={searchQuery} onChange={e => handleSearch(e.target.value)} placeholder="ابحث عن صفحة أو ميزة..." className="pr-10 h-10 rounded-xl border-2 bg-stone-50 dark:bg-stone-700 dark:text-white" />
            {searchResults && searchResults.length > 0 && (<div className="absolute top-12 right-0 w-full bg-white dark:bg-stone-800 rounded-xl shadow-2xl border dark:border-stone-700 p-2 z-50">{searchResults.map((r, i) => (<button key={i} onClick={() => { setSearchResults(null); setSearchQuery('') }} className="w-full text-right px-3 py-2 rounded-lg hover:bg-stone-100 dark:hover:bg-stone-700 text-sm font-bold dark:text-white">{r.name}</button>))}</div>)}
          </div>
          <Button variant="ghost" size="icon" className="relative"><Bell className="h-5 w-5 text-stone-500" /><span className="absolute top-1 right-1 w-2 h-2 bg-[#F5820D] rounded-full" /></Button>
        </div>
        <div className="p-6">
          {activeModule === 'dashboard' && <DashboardView />}
          {activeModule === 'clients' && <ClientsView />}
          {activeModule === 'hr' && <HRView />}
          {activeModule === 'accounting' && <AccountingView />}
          {activeModule === 'contracts' && <ContractsView />}
          {activeModule === 'projects' && <ProjectsView />}
          {activeModule === 'appointments' && <AppointmentsView />}
          {activeModule === 'construction' && <ConstructionView />}
          {activeModule === 'purchasing' && <PurchasingView />}
          {activeModule === 'warehouse' && <WarehouseView />}
          {activeModule === 'reports' && <ReportsView />}
          {activeModule === 'settings' && <SettingsView />}
        </div>
      </main>
      <SystemExpertChatWidget />
      <SyncStatusProvider><OfflineIndicator /></SyncStatusProvider>
    </div>
  )
}

// ═══ DASHBOARD ═══
function DashboardView() {
  const { data: k } = useQuery({ queryKey: ['dashboard'], queryFn: async () => { const r = await fetch('/api/dashboard'); if (!r.ok) return null; const j = await r.json(); return j.data?.kpis || null } })
  const d = k || { totalEmployees: 0, totalClients: 0, activeProjects: 0, totalRevenue: 0, pendingLeaveRequests: 0, pendingTasks: 0 }
  return (<div className="space-y-6"><div><h1 className="text-2xl font-black text-stone-800 dark:text-white">لوحة التحكم</h1><p className="text-sm text-stone-500">نظرة عامة على النظام</p></div>
    <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
      <Kpi icon={Users} label="العملاء" value={d.totalClients} color="bg-blue-50 text-blue-600" />
      <Kpi icon={Briefcase} label="المشاريع" value={d.activeProjects} color="bg-purple-50 text-purple-600" />
      <Kpi icon={DollarSign} label="الإيرادات" value={KWD(d.totalRevenue)} color="bg-emerald-50 text-emerald-600" />
      <Kpi icon={UserCircle} label="الموظفون" value={d.totalEmployees} color="bg-sky-50 text-sky-600" />
      <Kpi icon={CalendarDays} label="إجازات معلقة" value={d.pendingLeaveRequests} color="bg-orange-50 text-orange-600" />
      <Kpi icon={FileText} label="مهام معلقة" value={d.pendingTasks} color="bg-rose-50 text-rose-600" />
    </div>
    <Card className="rounded-2xl border border-stone-200 dark:border-stone-700"><CardHeader><CardTitle className="text-lg dark:text-white">مرحباً بك في Nova ERP</CardTitle></CardHeader><CardContent><p className="text-sm text-stone-600 dark:text-stone-300 leading-relaxed">نظام إدارة موارد المؤسسات المصمم خصيصاً لمكاتب الهندسة وشركات المقاولات في الكويت. يدعم القانون الكويتي (المواد 41، 51، 53)، المحافظات الكويتية، الدينار الكويتي، والعربية بـ RTL كامل.</p><div className="flex flex-wrap gap-2 mt-4"><Badge className="bg-orange-50 text-[#F5820D]">قانون العمل الكويتي</Badge><Badge className="bg-emerald-50 text-emerald-600">66 حساب محاسبي</Badge><Badge className="bg-blue-50 text-blue-600">ربط العقد بالدفعات</Badge><Badge className="bg-purple-50 text-purple-600">صلاحيات ذكية</Badge><Badge className="bg-rose-50 text-rose-600">ذكاء اصطناعي</Badge></div></CardContent></Card>
  </div>)
}
function Kpi({ icon: Icon, label, value, color }: any) { return <Card className="rounded-2xl border border-stone-200 dark:border-stone-700 overflow-hidden"><CardContent className="p-4 flex items-center gap-3"><div className={cn('w-12 h-12 rounded-2xl flex items-center justify-center', color)}><Icon className="h-5 w-5" /></div><div><p className="text-xs text-stone-500 font-medium">{label}</p><p className="text-lg font-black text-stone-800 dark:text-white">{value}</p></div></CardContent></Card> }

// ═══ CLIENTS (full CRUD) ═══
function ClientsView() {
  const [search, setSearch] = useState(''); const [showAdd, setShowAdd] = useState(false); const [showContract, setShowContract] = useState(false); const [selected, setSelected] = useState<any>(null)
  const [form, setForm] = useState({ nameAr: '', nameEn: '', mobile: '', phone: '', email: '', governorate: '', city: '', address: '', status: 'new', clientType: 'registered' })
  const qc = useQueryClient()
  const { data: clients, isLoading } = useQuery({ queryKey: ['clients'], queryFn: async () => { const r = await fetch('/api/clients?page=1&limit=200'); if (!r.ok) return []; const j = await r.json(); return j.data || [] } })
  const { data: governorates } = useQuery({ queryKey: ['govs'], queryFn: async () => { const r = await fetch('/api/governorates'); if (!r.ok) return []; const j = await r.json(); return j.data || [] } })
  const filtered = (clients || []).filter((c: any) => !search || (c.nameAr || '').includes(search) || (c.mobile || '').includes(search))
  const addMut = useMutation({ mutationFn: async (d: any) => fetch('/api/clients', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(d) }), onSuccess: () => { qc.invalidateQueries({ queryKey: ['clients'] }); setShowAdd(false); setForm({ nameAr: '', nameEn: '', mobile: '', phone: '', email: '', governorate: '', city: '', address: '', status: 'new', clientType: 'registered' }) } })
  const delMut = useMutation({ mutationFn: async (id: string) => fetch(`/api/clients/${id}`, { method: 'DELETE' }), onSuccess: () => qc.invalidateQueries({ queryKey: ['clients'] }) })
  return (<div className="space-y-6">
    <div className="flex items-center justify-between"><div><h1 className="text-2xl font-black text-stone-800 dark:text-white">العملاء</h1><p className="text-sm text-stone-500">{filtered.length} عميل</p></div><Button onClick={() => setShowAdd(true)} className="gap-2 bg-[#F5820D] hover:bg-[#C45600]"><Plus className="h-4 w-4" /> عميل جديد</Button></div>
    <div className="relative max-w-sm"><Search className="absolute right-3 top-1/2 -translate-y-1/2 h-4 w-4 text-stone-400" /><Input value={search} onChange={e => setSearch(e.target.value)} placeholder="ابحث..." className="pr-10 h-11 rounded-xl border-2" /></div>
    <Card className="rounded-2xl border overflow-hidden"><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-stone-50 border-b dark:bg-stone-800"><tr><th className="text-right p-3 font-bold dark:text-white">الاسم</th><th className="text-right p-3 font-bold dark:text-white">الجوال</th><th className="text-right p-3 font-bold dark:text-white">المحافظة</th><th className="text-right p-3 font-bold dark:text-white">الحالة</th><th className="text-right p-3 font-bold dark:text-white">إجراءات</th></tr></thead><tbody className="divide-y divide-stone-100 dark:divide-stone-700">
      {isLoading && <tr><td colSpan={5} className="text-center py-8"><Loader2 className="h-6 w-6 animate-spin mx-auto text-stone-400" /></td></tr>}
      {filtered.map((c: any) => (<tr key={c.id} className="hover:bg-stone-50 dark:hover:bg-stone-800"><td className="p-3 font-bold dark:text-white">{c.nameAr || c.nameEn || '—'}</td><td className="p-3 text-stone-600 dark:text-stone-300">{c.mobile || '—'}</td><td className="p-3 text-stone-600 dark:text-stone-300">{c.governorate || '—'}</td><td className="p-3"><Badge className={c.status === 'contracted' ? 'bg-emerald-50 text-emerald-600' : 'bg-blue-50 text-blue-600'}>{c.status === 'contracted' ? 'متعاقد' : 'جديد'}</Badge></td><td className="p-3"><div className="flex gap-1"><Button variant="ghost" size="icon" className="h-8 w-8" onClick={() => { setSelected(c); setShowContract(true) }}><FileText className="h-4 w-4 text-[#F5820D]" /></Button><Button variant="ghost" size="icon" className="h-8 w-8 text-red-500" onClick={() => { if (confirm('حذف؟')) delMut.mutate(c.id) }}><Trash2 className="h-4 w-4" /></Button></div></td></tr>))}
    </tbody></table></div></Card>
    <Dialog open={showAdd} onOpenChange={setShowAdd}><DialogContent dir="rtl" className="max-w-md rounded-2xl"><DialogHeader><DialogTitle className="font-black">إضافة عميل</DialogTitle></DialogHeader>
      <div className="space-y-3 p-4">
        <div className="grid grid-cols-2 gap-3"><div><Label className="font-bold">الاسم (عربي) *</Label><Input value={form.nameAr} onChange={e => setForm({ ...form, nameAr: e.target.value })} className="h-11 rounded-xl border-2" /></div><div><Label className="font-bold">الجوال *</Label><Input value={form.mobile} onChange={e => setForm({ ...form, mobile: e.target.value })} className="h-11 rounded-xl border-2" /></div></div>
        <div><Label className="font-bold">البريد</Label><Input value={form.email} onChange={e => setForm({ ...form, email: e.target.value })} className="h-11 rounded-xl border-2" /></div>
        <div><Label className="font-bold">المحافظة</Label><Select value={form.governorate} onValueChange={v => setForm({ ...form, governorate: v })}><SelectTrigger className="h-11 rounded-xl border-2"><SelectValue placeholder="اختر..." /></SelectTrigger><SelectContent dir="rtl">{(governorates || []).map((g: any) => <SelectItem key={g.id} value={g.name}>{g.name}</SelectItem>)}</SelectContent></Select></div>
        <div><Label className="font-bold">العنوان</Label><Input value={form.address} onChange={e => setForm({ ...form, address: e.target.value })} className="h-11 rounded-xl border-2" /></div>
      </div>
      <DialogFooter><Button variant="outline" onClick={() => setShowAdd(false)}>إلغاء</Button><Button onClick={() => addMut.mutate(form)} disabled={!form.nameAr || !form.mobile} className="bg-[#F5820D] hover:bg-[#C45600]">حفظ</Button></DialogFooter>
    </DialogContent></Dialog>
    {selected && <ContractClausesForm isOpen={showContract} onClose={() => { setShowContract(false); setSelected(null) }} transaction={null} clientId={selected.id} clientName={selected.nameAr} />}
  </div>)
}

// ═══ HR (full CRUD + approve/reject) ═══
function HRView() {
  const [tab, setTab] = useState<'employees' | 'gratuity' | 'leaves'>('employees')
  const [showLeave, setShowLeave] = useState(false); const [showAddEmp, setShowAddEmp] = useState(false)
  const [empForm, setEmpForm] = useState({ fullName: '', department: '', jobTitle: '', basicSalary: '', housingAllowance: '', transportAllowance: '', mobile: '', civilId: '', hireDate: '' })
  const qc = useQueryClient()
  const { data: employees, isLoading } = useQuery({ queryKey: ['employees'], queryFn: async () => { const r = await fetch('/api/employees?limit=200'); if (!r.ok) return []; const j = await r.json(); return j.data || [] } })
  const { data: leaves } = useQuery({ queryKey: ['leaves'], queryFn: async () => { const r = await fetch('/api/leave-requests'); if (!r.ok) return []; const j = await r.json(); return j.data || [] } })
  const { data: departments } = useQuery({ queryKey: ['depts'], queryFn: async () => { const r = await fetch('/api/departments'); if (!r.ok) return []; const j = await r.json(); return j.data || [] } })
  const addEmpMut = useMutation({ mutationFn: async (d: any) => fetch('/api/employees', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(d) }), onSuccess: () => { qc.invalidateQueries({ queryKey: ['employees'] }); setShowAddEmp(false); setEmpForm({ fullName: '', department: '', jobTitle: '', basicSalary: '', housingAllowance: '', transportAllowance: '', mobile: '', civilId: '', hireDate: '' }) } })
  const approveMut = useMutation({ mutationFn: async ({ id, status }: { id: string; status: string }) => fetch(`/api/leave-requests/${id}`, { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ status, approvedBy: 'admin' }) }), onSuccess: () => qc.invalidateQueries({ queryKey: ['leaves'] }) })
  return (<div className="space-y-4">
    <div className="flex items-center justify-between"><h1 className="text-2xl font-black text-stone-800 dark:text-white">الموارد البشرية</h1>{tab === 'employees' && <Button onClick={() => setShowAddEmp(true)} className="gap-2 bg-[#F5820D] hover:bg-[#C45600]"><Plus className="h-4 w-4" /> موظف جديد</Button>}</div>
    <div className="flex gap-2 flex-wrap"><button onClick={() => setTab('employees')} className={cn('px-4 py-2 rounded-xl text-sm font-bold', tab === 'employees' ? 'bg-[#F5820D] text-white' : 'bg-white border text-stone-600 dark:bg-stone-800 dark:text-stone-300')}>الموظفون ({employees?.length || 0})</button><button onClick={() => setTab('gratuity')} className={cn('px-4 py-2 rounded-xl text-sm font-bold', tab === 'gratuity' ? 'bg-[#F5820D] text-white' : 'bg-white border text-stone-600 dark:bg-stone-800 dark:text-stone-300')}>حاسبة المكافأة</button><button onClick={() => setTab('leaves')} className={cn('px-4 py-2 rounded-xl text-sm font-bold', tab === 'leaves' ? 'bg-[#F5820D] text-white' : 'bg-white border text-stone-600 dark:bg-stone-800 dark:text-stone-300')}>الإجازات ({leaves?.length || 0})</button></div>
    {tab === 'employees' && <Card className="rounded-2xl border overflow-hidden"><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-stone-50 border-b dark:bg-stone-800"><tr><th className="text-right p-3 font-bold dark:text-white">الاسم</th><th className="text-right p-3 font-bold dark:text-white">الرقم</th><th className="text-right p-3 font-bold dark:text-white">القسم</th><th className="text-right p-3 font-bold dark:text-white">المسمى</th><th className="text-right p-3 font-bold dark:text-white">الراتب</th><th className="text-right p-3 font-bold dark:text-white">الحالة</th></tr></thead><tbody className="divide-y divide-stone-100 dark:divide-stone-700">{isLoading && <tr><td colSpan={6} className="text-center py-8"><Loader2 className="h-6 w-6 animate-spin mx-auto text-stone-400" /></td></tr>}{(employees || []).map((e: any) => (<tr key={e.id} className="hover:bg-stone-50 dark:hover:bg-stone-800"><td className="p-3 font-bold dark:text-white">{e.fullName}</td><td className="p-3 font-mono text-stone-600 dark:text-stone-300">{e.employeeNumber}</td><td className="p-3 text-stone-600 dark:text-stone-300">{e.department || '—'}</td><td className="p-3 text-stone-600 dark:text-stone-300">{e.jobTitle || '—'}</td><td className="p-3 font-mono dark:text-stone-300">{KWD(e.totalSalary || 0)}</td><td className="p-3"><Badge className={e.status === 'active' ? 'bg-emerald-50 text-emerald-600' : 'bg-red-50 text-red-600'}>{e.status === 'active' ? 'نشط' : 'منتهي'}</Badge></td></tr>))}</tbody></table></div></Card>}
    {tab === 'gratuity' && <GratuityCalculatorView />}
    {tab === 'leaves' && (<div className="space-y-4"><Button onClick={() => setShowLeave(true)} className="gap-2 bg-[#F5820D] hover:bg-[#C45600]"><Plus className="h-4 w-4" /> طلب إجازة</Button><Card className="rounded-2xl border overflow-hidden"><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-stone-50 border-b dark:bg-stone-800"><tr><th className="text-right p-3 font-bold dark:text-white">الموظف</th><th className="text-right p-3 font-bold dark:text-white">النوع</th><th className="text-right p-3 font-bold dark:text-white">من</th><th className="text-right p-3 font-bold dark:text-white">إلى</th><th className="text-right p-3 font-bold dark:text-white">أيام</th><th className="text-right p-3 font-bold dark:text-white">الحالة</th><th className="text-right p-3 font-bold dark:text-white">إجراءات</th></tr></thead><tbody className="divide-y divide-stone-100 dark:divide-stone-700">{(leaves || []).map((l: any) => (<tr key={l.id} className="hover:bg-stone-50 dark:hover:bg-stone-800"><td className="p-3 font-bold dark:text-white">{l.employee?.fullName || '—'}</td><td className="p-3 dark:text-stone-300">{l.leaveType === 'Annual' ? 'سنوية' : l.leaveType === 'Sick' ? 'مرضية' : l.leaveType}</td><td className="p-3 text-stone-600 dark:text-stone-300">{l.startDate ? new Date(l.startDate).toLocaleDateString('ar-KW') : '—'}</td><td className="p-3 text-stone-600 dark:text-stone-300">{l.endDate ? new Date(l.endDate).toLocaleDateString('ar-KW') : '—'}</td><td className="p-3 dark:text-stone-300">{l.totalDays}</td><td className="p-3"><Badge className={l.status === 'pending' ? 'bg-amber-50 text-amber-600' : l.status === 'approved' ? 'bg-emerald-50 text-emerald-600' : 'bg-red-50 text-red-600'}>{l.status === 'pending' ? 'معلق' : l.status === 'approved' ? 'موافق' : 'مرفوض'}</Badge></td><td className="p-3">{l.status === 'pending' && <div className="flex gap-1"><Button variant="ghost" size="icon" className="h-8 w-8 text-emerald-600" onClick={() => approveMut.mutate({ id: l.id, status: 'approved' })}><CheckCircle className="h-4 w-4" /></Button><Button variant="ghost" size="icon" className="h-8 w-8 text-red-500" onClick={() => approveMut.mutate({ id: l.id, status: 'rejected' })}><XCircle className="h-4 w-4" /></Button></div>}</td></tr>))}</tbody></table></div></Card><LeaveRequestForm isOpen={showLeave} onClose={() => setShowLeave(false)} onSaveSuccess={() => qc.invalidateQueries({ queryKey: ['leaves'] })} /></div>)}
    <Dialog open={showAddEmp} onOpenChange={setShowAddEmp}><DialogContent dir="rtl" className="max-w-md rounded-2xl"><DialogHeader><DialogTitle className="font-black">إضافة موظف</DialogTitle></DialogHeader><div className="space-y-3 p-4">
      <div><Label className="font-bold">الاسم *</Label><Input value={empForm.fullName} onChange={e => setEmpForm({ ...empForm, fullName: e.target.value })} className="h-11 rounded-xl border-2" /></div>
      <div className="grid grid-cols-2 gap-3"><div><Label className="font-bold">القسم</Label><Select value={empForm.department} onValueChange={v => setEmpForm({ ...empForm, department: v })}><SelectTrigger className="h-11 rounded-xl border-2"><SelectValue placeholder="اختر..." /></SelectTrigger><SelectContent dir="rtl">{(departments || []).map((d: any) => <SelectItem key={d.id} value={d.name}>{d.name}</SelectItem>)}</SelectContent></Select></div><div><Label className="font-bold">المسمى</Label><Input value={empForm.jobTitle} onChange={e => setEmpForm({ ...empForm, jobTitle: e.target.value })} className="h-11 rounded-xl border-2" /></div></div>
      <div className="grid grid-cols-3 gap-3"><div><Label className="font-bold">الأساسي</Label><Input type="number" value={empForm.basicSalary} onChange={e => setEmpForm({ ...empForm, basicSalary: e.target.value })} className="h-11 rounded-xl border-2" /></div><div><Label className="font-bold">سكن</Label><Input type="number" value={empForm.housingAllowance} onChange={e => setEmpForm({ ...empForm, housingAllowance: e.target.value })} className="h-11 rounded-xl border-2" /></div><div><Label className="font-bold">مواصلات</Label><Input type="number" value={empForm.transportAllowance} onChange={e => setEmpForm({ ...empForm, transportAllowance: e.target.value })} className="h-11 rounded-xl border-2" /></div></div>
      <div className="grid grid-cols-2 gap-3"><div><Label className="font-bold">الجوال</Label><Input value={empForm.mobile} onChange={e => setEmpForm({ ...empForm, mobile: e.target.value })} className="h-11 rounded-xl border-2" /></div><div><Label className="font-bold">الرقم المدني</Label><Input value={empForm.civilId} onChange={e => setEmpForm({ ...empForm, civilId: e.target.value })} className="h-11 rounded-xl border-2" /></div></div>
      <div><Label className="font-bold">تاريخ التعيين</Label><Input type="date" value={empForm.hireDate} onChange={e => setEmpForm({ ...empForm, hireDate: e.target.value })} className="h-11 rounded-xl border-2" /></div>
    </div><DialogFooter><Button variant="outline" onClick={() => setShowAddEmp(false)}>إلغاء</Button><Button onClick={() => addEmpMut.mutate(empForm)} disabled={!empForm.fullName} className="bg-[#F5820D] hover:bg-[#C45600]">حفظ</Button></DialogFooter></DialogContent></Dialog>
  </div>)
}

// ═══ ACCOUNTING ═══
function AccountingView() {
  const [tab, setTab] = useState<'journal' | 'receipts' | 'vouchers' | 'accounts'>('accounts')
  const { data: accounts } = useQuery({ queryKey: ['accounts'], queryFn: async () => { const r = await fetch('/api/accounts'); if (!r.ok) return []; const j = await r.json(); return j.data || [] } })
  const { data: journal } = useQuery({ queryKey: ['journal'], queryFn: async () => { const r = await fetch('/api/journal-entries'); if (!r.ok) return []; const j = await r.json(); return j.data || [] } })
  const { data: receipts } = useQuery({ queryKey: ['receipts'], queryFn: async () => { const r = await fetch('/api/cash-receipts'); if (!r.ok) return []; const j = await r.json(); return j.data || [] } })
  const { data: vouchers } = useQuery({ queryKey: ['vouchers'], queryFn: async () => { const r = await fetch('/api/payment-vouchers'); if (!r.ok) return []; const j = await r.json(); return j.data || [] } })
  const typeBadge = (t: string) => t === 'asset' ? 'bg-blue-50 text-blue-600' : t === 'liability' ? 'bg-red-50 text-red-600' : t === 'equity' ? 'bg-purple-50 text-purple-600' : t === 'income' ? 'bg-emerald-50 text-emerald-600' : 'bg-orange-50 text-orange-600'
  const typeLabel = (t: string) => t === 'asset' ? 'أصول' : t === 'liability' ? 'التزامات' : t === 'equity' ? 'حقوق ملكية' : t === 'income' ? 'إيرادات' : 'مصروفات'
  return (<div className="space-y-4"><h1 className="text-2xl font-black text-stone-800 dark:text-white">المحاسبة</h1>
    <div className="flex gap-2 flex-wrap"><button onClick={() => setTab('accounts')} className={cn('px-4 py-2 rounded-xl text-sm font-bold', tab === 'accounts' ? 'bg-[#F5820D] text-white' : 'bg-white border dark:bg-stone-800 dark:text-stone-300')}>شجرة الحسابات ({accounts?.length || 0})</button><button onClick={() => setTab('journal')} className={cn('px-4 py-2 rounded-xl text-sm font-bold', tab === 'journal' ? 'bg-[#F5820D] text-white' : 'bg-white border dark:bg-stone-800 dark:text-stone-300')}>القيود ({journal?.length || 0})</button><button onClick={() => setTab('receipts')} className={cn('px-4 py-2 rounded-xl text-sm font-bold', tab === 'receipts' ? 'bg-[#F5820D] text-white' : 'bg-white border dark:bg-stone-800 dark:text-stone-300')}>سندات القبض ({receipts?.length || 0})</button><button onClick={() => setTab('vouchers')} className={cn('px-4 py-2 rounded-xl text-sm font-bold', tab === 'vouchers' ? 'bg-[#F5820D] text-white' : 'bg-white border dark:bg-stone-800 dark:text-stone-300')}>سندات الصرف ({vouchers?.length || 0})</button></div>
    {tab === 'accounts' && <Card className="rounded-2xl border overflow-hidden"><div className="overflow-x-auto max-h-[60vh] overflow-y-auto"><table className="w-full text-sm"><thead className="bg-stone-50 border-b sticky top-0 dark:bg-stone-800"><tr><th className="text-right p-3 font-bold dark:text-white">الكود</th><th className="text-right p-3 font-bold dark:text-white">الاسم</th><th className="text-right p-3 font-bold dark:text-white">النوع</th><th className="text-right p-3 font-bold dark:text-white">المستوى</th></tr></thead><tbody className="divide-y divide-stone-100 dark:divide-stone-700">{(accounts || []).map((a: any) => (<tr key={a.id} className="hover:bg-stone-50 dark:hover:bg-stone-800"><td className="p-3 font-mono font-bold text-[#F5820D]">{a.code}</td><td className="p-3 dark:text-white">{a.name}</td><td className="p-3"><Badge className={typeBadge(a.type)}>{typeLabel(a.type)}</Badge></td><td className="p-3 text-stone-600 dark:text-stone-300">{a.level}</td></tr>))}</tbody></table></div></Card>}
    {tab === 'journal' && <Card className="rounded-2xl border overflow-hidden"><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-stone-50 border-b dark:bg-stone-800"><tr><th className="text-right p-3 font-bold dark:text-white">رقم القيد</th><th className="text-right p-3 font-bold dark:text-white">التاريخ</th><th className="text-right p-3 font-bold dark:text-white">الوصف</th><th className="text-right p-3 font-bold dark:text-white">مدين</th><th className="text-right p-3 font-bold dark:text-white">دائن</th><th className="text-right p-3 font-bold dark:text-white">الحالة</th></tr></thead><tbody className="divide-y divide-stone-100 dark:divide-stone-700">{(journal || []).map((j: any) => (<tr key={j.id} className="hover:bg-stone-50 dark:hover:bg-stone-800"><td className="p-3 font-mono font-bold dark:text-white">{j.entryNumber}</td><td className="p-3 text-stone-600 dark:text-stone-300">{new Date(j.date).toLocaleDateString('ar-KW')}</td><td className="p-3 dark:text-stone-300">{j.description || '—'}</td><td className="p-3 font-mono dark:text-stone-300">{KWD(j.totalDebit)}</td><td className="p-3 font-mono dark:text-stone-300">{KWD(j.totalCredit)}</td><td className="p-3"><Badge className={j.status === 'posted' ? 'bg-emerald-50 text-emerald-600' : 'bg-amber-50 text-amber-600'}>{j.status === 'posted' ? 'مرحّل' : 'مسودة'}</Badge></td></tr>))}</tbody></table></div></Card>}
    {tab === 'receipts' && <Card className="rounded-2xl border overflow-hidden"><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-stone-50 border-b dark:bg-stone-800"><tr><th className="text-right p-3 font-bold dark:text-white">رقم السند</th><th className="text-right p-3 font-bold dark:text-white">العميل</th><th className="text-right p-3 font-bold dark:text-white">المبلغ</th><th className="text-right p-3 font-bold dark:text-white">التاريخ</th><th className="text-right p-3 font-bold dark:text-white">الحالة</th></tr></thead><tbody className="divide-y divide-stone-100 dark:divide-stone-700">{(receipts || []).map((r: any) => (<tr key={r.id} className="hover:bg-stone-50 dark:hover:bg-stone-800"><td className="p-3 font-mono font-bold dark:text-white">{r.receiptNumber}</td><td className="p-3 dark:text-stone-300">{r.client?.nameAr || '—'}</td><td className="p-3 font-mono font-bold text-emerald-600">{KWD(r.amount)}</td><td className="p-3 text-stone-600 dark:text-stone-300">{new Date(r.date).toLocaleDateString('ar-KW')}</td><td className="p-3"><Badge className={r.status === 'posted' ? 'bg-emerald-50 text-emerald-600' : 'bg-amber-50 text-amber-600'}>{r.status === 'posted' ? 'مرحّل' : 'مسودة'}</Badge></td></tr>))}</tbody></table></div></Card>}
    {tab === 'vouchers' && <Card className="rounded-2xl border overflow-hidden"><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-stone-50 border-b dark:bg-stone-800"><tr><th className="text-right p-3 font-bold dark:text-white">رقم السند</th><th className="text-right p-3 font-bold dark:text-white">المستفيد</th><th className="text-right p-3 font-bold dark:text-white">المبلغ</th><th className="text-right p-3 font-bold dark:text-white">التاريخ</th><th className="text-right p-3 font-bold dark:text-white">الحالة</th></tr></thead><tbody className="divide-y divide-stone-100 dark:divide-stone-700">{(vouchers || []).map((v: any) => (<tr key={v.id} className="hover:bg-stone-50 dark:hover:bg-stone-800"><td className="p-3 font-mono font-bold dark:text-white">{v.voucherNumber}</td><td className="p-3 dark:text-stone-300">{v.payeeName || '—'}</td><td className="p-3 font-mono font-bold text-red-600">{KWD(v.amount)}</td><td className="p-3 text-stone-600 dark:text-stone-300">{new Date(v.date).toLocaleDateString('ar-KW')}</td><td className="p-3"><Badge className={v.status === 'posted' ? 'bg-emerald-50 text-emerald-600' : 'bg-amber-50 text-amber-600'}>{v.status === 'posted' ? 'مرحّل' : 'مسودة'}</Badge></td></tr>))}</tbody></table></div></Card>}
  </div>)
}

// ═══ CONTRACTS ═══
function ContractsView() {
  const [showActivate, setShowActivate] = useState(false)
  const { data: quotations } = useQuery({ queryKey: ['quotations'], queryFn: async () => { const r = await fetch('/api/quotations'); if (!r.ok) return []; const j = await r.json(); return j.data || [] } })
  const { data: contracts } = useQuery({ queryKey: ['contracts'], queryFn: async () => { const r = await fetch('/api/contracts'); if (!r.ok) return []; const j = await r.json(); return j.data || [] } })
  return (<div className="space-y-6"><div className="flex items-center justify-between"><div><h1 className="text-2xl font-black text-stone-800 dark:text-white">العقود وعروض الأسعار</h1><p className="text-sm text-stone-500">{quotations?.length || 0} عرض • {contracts?.length || 0} عقد</p></div><Button onClick={() => setShowActivate(true)} className="gap-2 bg-[#F5820D] hover:bg-[#C45600]"><FileText className="h-4 w-4" /> تفعيل عقد</Button></div>
    <Card className="rounded-2xl border overflow-hidden"><CardHeader><CardTitle className="text-base dark:text-white">عروض الأسعار</CardTitle></CardHeader><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-stone-50 border-b dark:bg-stone-800"><tr><th className="text-right p-3 font-bold dark:text-white">رقم العرض</th><th className="text-right p-3 font-bold dark:text-white">العميل</th><th className="text-right p-3 font-bold dark:text-white">المبلغ</th><th className="text-right p-3 font-bold dark:text-white">الحالة</th></tr></thead><tbody className="divide-y divide-stone-100 dark:divide-stone-700">{(quotations || []).map((q: any) => (<tr key={q.id} className="hover:bg-stone-50 dark:hover:bg-stone-800"><td className="p-3 font-mono font-bold dark:text-white">{q.quotationNumber}</td><td className="p-3 dark:text-stone-300">{q.client?.nameAr || '—'}</td><td className="p-3 font-mono dark:text-stone-300">{KWD(q.totalAmount)}</td><td className="p-3"><Badge className={q.status === 'accepted' ? 'bg-emerald-50 text-emerald-600' : 'bg-amber-50 text-amber-600'}>{q.status === 'accepted' ? 'مقبول' : 'مسودة'}</Badge></td></tr>))}</tbody></table></div></Card>
    {contracts && contracts.length > 0 && <Card className="rounded-2xl border overflow-hidden"><CardHeader><CardTitle className="text-base dark:text-white">العقود المفعّلة</CardTitle></CardHeader><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-stone-50 border-b dark:bg-stone-800"><tr><th className="text-right p-3 font-bold dark:text-white">العميل</th><th className="text-right p-3 font-bold dark:text-white">المبلغ</th><th className="text-right p-3 font-bold dark:text-white">البنود</th><th className="text-right p-3 font-bold dark:text-white">الحالة</th></tr></thead><tbody className="divide-y divide-stone-100 dark:divide-stone-700">{contracts.map((c: any) => (<tr key={c.id} className="hover:bg-stone-50 dark:hover:bg-stone-800"><td className="p-3 dark:text-stone-300">{c.transaction?.client?.nameAr || '—'}</td><td className="p-3 font-mono dark:text-stone-300">{KWD(c.totalAmount)}</td><td className="p-3 dark:text-stone-300">{c.milestones?.length || 0}</td><td className="p-3"><Badge className={c.status === 'active' ? 'bg-emerald-50 text-emerald-600' : 'bg-amber-50 text-amber-600'}>{c.status === 'active' ? 'نشط' : c.status}</Badge></td></tr>))}</tbody></table></div></Card>}
    <ContractClausesForm isOpen={showActivate} onClose={() => setShowActivate(false)} transaction={null} clientId="client-1" clientName="عميل جديد" />
  </div>)
}

// ═══ PROJECTS ═══
function ProjectsView() {
  const { data: projects, isLoading } = useQuery({ queryKey: ['projects'], queryFn: async () => { const r = await fetch('/api/projects'); if (!r.ok) return []; const j = await r.json(); return j.data || [] } })
  return (<div className="space-y-4"><h1 className="text-2xl font-black text-stone-800 dark:text-white">المشاريع</h1><div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">{isLoading && <Card className="rounded-2xl border p-8"><Loader2 className="h-6 w-6 animate-spin mx-auto text-stone-400" /></Card>}{(projects || []).map((p: any) => (<Card key={p.id} className="rounded-2xl border overflow-hidden hover:shadow-lg transition-shadow dark:border-stone-700"><CardHeader className="bg-stone-50 dark:bg-stone-800 pb-3"><div className="flex items-center justify-between"><CardTitle className="text-base font-black dark:text-white">{p.name}</CardTitle><Badge className={p.status === 'in-progress' ? 'bg-emerald-50 text-emerald-600' : 'bg-blue-50 text-blue-600'}>{p.status === 'in-progress' ? 'قيد التنفيذ' : 'تخطيط'}</Badge></div></CardHeader><CardContent className="p-4 space-y-2"><div className="flex justify-between text-sm"><span className="text-stone-500">العميل</span><span className="font-bold dark:text-stone-300">{p.client?.nameAr || '—'}</span></div><div className="flex justify-between text-sm"><span className="text-stone-500">الميزانية</span><span className="font-bold font-mono dark:text-stone-300">{KWD(p.totalBudget)}</span></div><div className="flex justify-between text-sm"><span className="text-stone-500">الإنجاز</span><span className="font-bold dark:text-stone-300">{p.progressPercent}%</span></div><div className="w-full h-2 bg-stone-100 rounded-full overflow-hidden"><div className="h-full bg-[#F5820D] rounded-full" style={{ width: `${p.progressPercent}%` }} /></div></CardContent></Card>))}</div></div>)
}

// ═══ APPOINTMENTS ═══
function AppointmentsView() {
  const { data: appts, isLoading } = useQuery({ queryKey: ['appointments'], queryFn: async () => { const r = await fetch('/api/appointments'); if (!r.ok) return []; const j = await r.json(); return j.data || [] } })
  return (<div className="space-y-4"><h1 className="text-2xl font-black text-stone-800 dark:text-white">المواعيد</h1><Card className="rounded-2xl border overflow-hidden"><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-stone-50 border-b dark:bg-stone-800"><tr><th className="text-right p-3 font-bold dark:text-white">العنوان</th><th className="text-right p-3 font-bold dark:text-white">العميل</th><th className="text-right p-3 font-bold dark:text-white">التاريخ</th><th className="text-right p-3 font-bold dark:text-white">النوع</th><th className="text-right p-3 font-bold dark:text-white">الحالة</th></tr></thead><tbody className="divide-y divide-stone-100 dark:divide-stone-700">{isLoading && <tr><td colSpan={5} className="text-center py-8"><Loader2 className="h-6 w-6 animate-spin mx-auto text-stone-400" /></td></tr>}{(appts || []).map((a: any) => (<tr key={a.id} className="hover:bg-stone-50 dark:hover:bg-stone-800"><td className="p-3 font-bold dark:text-white">{a.title}</td><td className="p-3 dark:text-stone-300">{a.clientName || '—'}</td><td className="p-3 dark:text-stone-300">{a.appointmentDate ? new Date(a.appointmentDate).toLocaleDateString('ar-KW') : '—'}</td><td className="p-3"><Badge className="bg-cyan-50 text-cyan-600">{a.type === 'site-visit' ? 'زيارة' : 'اجتماع'}</Badge></td><td className="p-3"><Badge className={a.status === 'scheduled' ? 'bg-amber-50 text-amber-600' : 'bg-emerald-50 text-emerald-600'}>{a.status === 'scheduled' ? 'مجدول' : 'مؤكد'}</Badge></td></tr>))}</tbody></table></div></Card></div>)
}

// ═══ CONSTRUCTION ═══
function ConstructionView() {
  const { data: projects } = useQuery({ queryKey: ['projects-c'], queryFn: async () => { const r = await fetch('/api/projects'); if (!r.ok) return []; const j = await r.json(); return j.data || [] } })
  return (<div className="space-y-4"><h1 className="text-2xl font-black text-stone-800 dark:text-white">المقاولات</h1><div className="grid grid-cols-1 md:grid-cols-3 gap-4"><Card className="rounded-2xl border p-6 dark:border-stone-700"><Briefcase className="h-8 w-8 text-purple-600 mb-2" /><p className="text-2xl font-black dark:text-white">{projects?.length || 0}</p><p className="text-sm text-stone-500">مشاريع</p></Card><Card className="rounded-2xl border p-6 dark:border-stone-700"><HardHat className="h-8 w-8 text-amber-600 mb-2" /><p className="text-2xl font-black dark:text-white">0</p><p className="text-sm text-stone-500">زيارات ميدانية</p></Card><Card className="rounded-2xl border p-6 dark:border-stone-700"><FileText className="h-8 w-8 text-orange-600 mb-2" /><p className="text-2xl font-black dark:text-white">0</p><p className="text-sm text-stone-500">مستخلصات</p></Card></div><Card className="rounded-2xl border overflow-hidden"><CardHeader><CardTitle className="text-base dark:text-white">المشاريع النشطة</CardTitle></CardHeader><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-stone-50 border-b dark:bg-stone-800"><tr><th className="text-right p-3 font-bold dark:text-white">المشروع</th><th className="text-right p-3 font-bold dark:text-white">العميل</th><th className="text-right p-3 font-bold dark:text-white">الحالة</th><th className="text-right p-3 font-bold dark:text-white">الإنجاز</th></tr></thead><tbody className="divide-y divide-stone-100 dark:divide-stone-700">{(projects || []).map((p: any) => (<tr key={p.id} className="hover:bg-stone-50 dark:hover:bg-stone-800"><td className="p-3 font-bold dark:text-white">{p.name}</td><td className="p-3 dark:text-stone-300">{p.client?.nameAr || '—'}</td><td className="p-3"><Badge className={p.status === 'in-progress' ? 'bg-emerald-50 text-emerald-600' : 'bg-blue-50 text-blue-600'}>{p.status === 'in-progress' ? 'قيد التنفيذ' : 'تخطيط'}</Badge></td><td className="p-3"><div className="flex items-center gap-2"><div className="w-20 h-2 bg-stone-100 rounded-full overflow-hidden"><div className="h-full bg-[#F5820D] rounded-full" style={{ width: `${p.progressPercent}%` }} /></div><span className="text-xs font-bold dark:text-stone-300">{p.progressPercent}%</span></div></td></tr>))}</tbody></table></div></Card></div>)
}

// ═══ PURCHASING ═══
function PurchasingView() {
  const [showAddVendor, setShowAddVendor] = useState(false)
  const [vendorForm, setVendorForm] = useState({ name: '', contactPerson: '', phone: '', email: '' })
  const qc = useQueryClient()
  const { data: vendors } = useQuery({ queryKey: ['vendors'], queryFn: async () => { const r = await fetch('/api/vendors'); if (!r.ok) return []; const j = await r.json(); return j.data || [] } })
  const { data: pos } = useQuery({ queryKey: ['pos'], queryFn: async () => { const r = await fetch('/api/purchase-orders'); if (!r.ok) return []; const j = await r.json(); return j.data || [] } })
  const addVendorMut = useMutation({ mutationFn: async (d: any) => fetch('/api/vendors', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(d) }), onSuccess: () => { qc.invalidateQueries({ queryKey: ['vendors'] }); setShowAddVendor(false); setVendorForm({ name: '', contactPerson: '', phone: '', email: '' }) } })
  return (<div className="space-y-4"><div className="flex items-center justify-between"><h1 className="text-2xl font-black text-stone-800 dark:text-white">المشتريات</h1><Button onClick={() => setShowAddVendor(true)} className="gap-2 bg-[#F5820D] hover:bg-[#C45600]"><Plus className="h-4 w-4" /> مورد جديد</Button></div>
    <div className="grid grid-cols-1 md:grid-cols-2 gap-4"><Card className="rounded-2xl border overflow-hidden dark:border-stone-700"><CardHeader><CardTitle className="text-base dark:text-white">الموردون ({vendors?.length || 0})</CardTitle></CardHeader><div className="divide-y divide-stone-100 dark:divide-stone-700">{(vendors || []).map((v: any) => (<div key={v.id} className="p-3 hover:bg-stone-50 dark:hover:bg-stone-800"><p className="font-bold text-sm dark:text-white">{v.name}</p><p className="text-xs text-stone-500">{v.contactPerson || '—'} • {v.phone || '—'}</p></div>))}</div></Card>
    <Card className="rounded-2xl border overflow-hidden dark:border-stone-700"><CardHeader><CardTitle className="text-base dark:text-white">أوامر الشراء ({pos?.length || 0})</CardTitle></CardHeader><div className="divide-y divide-stone-100 dark:divide-stone-700">{(pos || []).map((p: any) => (<div key={p.id} className="p-3 flex items-center justify-between hover:bg-stone-50 dark:hover:bg-stone-800"><div><p className="font-bold text-sm font-mono dark:text-white">{p.poNumber}</p><p className="text-xs text-stone-500">{p.vendor?.name || '—'}</p></div><Badge className={p.status === 'approved' ? 'bg-emerald-50 text-emerald-600' : 'bg-amber-50 text-amber-600'}>{p.status}</Badge></div>))}</div></Card></div>
    <Dialog open={showAddVendor} onOpenChange={setShowAddVendor}><DialogContent dir="rtl" className="max-w-md rounded-2xl"><DialogHeader><DialogTitle className="font-black">إضافة مورد</DialogTitle></DialogHeader><div className="space-y-3 p-4"><div><Label className="font-bold">الاسم *</Label><Input value={vendorForm.name} onChange={e => setVendorForm({ ...vendorForm, name: e.target.value })} className="h-11 rounded-xl border-2" /></div><div className="grid grid-cols-2 gap-3"><div><Label className="font-bold">جهة الاتصال</Label><Input value={vendorForm.contactPerson} onChange={e => setVendorForm({ ...vendorForm, contactPerson: e.target.value })} className="h-11 rounded-xl border-2" /></div><div><Label className="font-bold">الهاتف</Label><Input value={vendorForm.phone} onChange={e => setVendorForm({ ...vendorForm, phone: e.target.value })} className="h-11 rounded-xl border-2" /></div></div></div><DialogFooter><Button variant="outline" onClick={() => setShowAddVendor(false)}>إلغاء</Button><Button onClick={() => addVendorMut.mutate(vendorForm)} disabled={!vendorForm.name} className="bg-[#F5820D] hover:bg-[#C45600]">حفظ</Button></DialogFooter></DialogContent></Dialog>
  </div>)
}

// ═══ WAREHOUSE ═══
function WarehouseView() {
  const [showAdd, setShowAdd] = useState(false)
  const [itemForm, setItemForm] = useState({ name: '', sku: '', unit: '', unitPrice: '', costPrice: '' })
  const qc = useQueryClient()
  const { data: items } = useQuery({ queryKey: ['items'], queryFn: async () => { const r = await fetch('/api/items'); if (!r.ok) return []; const j = await r.json(); return j.data || [] } })
  const addItemMut = useMutation({ mutationFn: async (d: any) => fetch('/api/items', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(d) }), onSuccess: () => { qc.invalidateQueries({ queryKey: ['items'] }); setShowAdd(false); setItemForm({ name: '', sku: '', unit: '', unitPrice: '', costPrice: '' }) } })
  return (<div className="space-y-4"><div className="flex items-center justify-between"><h1 className="text-2xl font-black text-stone-800 dark:text-white">المخازن — الأصناف</h1><Button onClick={() => setShowAdd(true)} className="gap-2 bg-[#F5820D] hover:bg-[#C45600]"><Plus className="h-4 w-4" /> صنف جديد</Button></div>
    <Card className="rounded-2xl border overflow-hidden dark:border-stone-700"><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-stone-50 border-b dark:bg-stone-800"><tr><th className="text-right p-3 font-bold dark:text-white">الاسم</th><th className="text-right p-3 font-bold dark:text-white">SKU</th><th className="text-right p-3 font-bold dark:text-white">الوحدة</th><th className="text-right p-3 font-bold dark:text-white">سعر البيع</th><th className="text-right p-3 font-bold dark:text-white">التكلفة</th></tr></thead><tbody className="divide-y divide-stone-100 dark:divide-stone-700">{(items || []).map((i: any) => (<tr key={i.id} className="hover:bg-stone-50 dark:hover:bg-stone-800"><td className="p-3 font-bold dark:text-white">{i.name}</td><td className="p-3 font-mono dark:text-stone-300">{i.sku || '—'}</td><td className="p-3 dark:text-stone-300">{i.unit || '—'}</td><td className="p-3 font-mono dark:text-stone-300">{KWD(i.unitPrice)}</td><td className="p-3 font-mono text-stone-500">{KWD(i.costPrice)}</td></tr>))}</tbody></table></div></Card>
    <Dialog open={showAdd} onOpenChange={setShowAdd}><DialogContent dir="rtl" className="max-w-md rounded-2xl"><DialogHeader><DialogTitle className="font-black">إضافة صنف</DialogTitle></DialogHeader><div className="space-y-3 p-4"><div><Label className="font-bold">الاسم *</Label><Input value={itemForm.name} onChange={e => setItemForm({ ...itemForm, name: e.target.value })} className="h-11 rounded-xl border-2" /></div><div className="grid grid-cols-2 gap-3"><div><Label className="font-bold">SKU</Label><Input value={itemForm.sku} onChange={e => setItemForm({ ...itemForm, sku: e.target.value })} className="h-11 rounded-xl border-2" /></div><div><Label className="font-bold">الوحدة</Label><Input value={itemForm.unit} onChange={e => setItemForm({ ...itemForm, unit: e.target.value })} className="h-11 rounded-xl border-2" /></div></div><div className="grid grid-cols-2 gap-3"><div><Label className="font-bold">سعر البيع</Label><Input type="number" value={itemForm.unitPrice} onChange={e => setItemForm({ ...itemForm, unitPrice: e.target.value })} className="h-11 rounded-xl border-2" /></div><div><Label className="font-bold">التكلفة</Label><Input type="number" value={itemForm.costPrice} onChange={e => setItemForm({ ...itemForm, costPrice: e.target.value })} className="h-11 rounded-xl border-2" /></div></div></div><DialogFooter><Button variant="outline" onClick={() => setShowAdd(false)}>إلغاء</Button><Button onClick={() => addItemMut.mutate(itemForm)} disabled={!itemForm.name} className="bg-[#F5820D] hover:bg-[#C45600]">حفظ</Button></DialogFooter></DialogContent></Dialog>
  </div>)
}

// ═══ REPORTS ═══
function ReportsView() {
  const { data: k } = useQuery({ queryKey: ['dashboard'], queryFn: async () => { const r = await fetch('/api/dashboard'); if (!r.ok) return null; const j = await r.json(); return j.data?.kpis || null } })
  const d = k || { totalEmployees: 0, totalClients: 0, activeProjects: 0, totalRevenue: 0, pendingLeaveRequests: 0, pendingTasks: 0 }
  return (<div className="space-y-6"><h1 className="text-2xl font-black text-stone-800 dark:text-white">التقارير</h1><div className="grid grid-cols-1 md:grid-cols-2 gap-4"><Card className="rounded-2xl border p-6 dark:border-stone-700"><h3 className="font-black text-stone-800 dark:text-white mb-3">ملخص الموارد البشرية</h3><div className="space-y-2 text-sm"><div className="flex justify-between"><span className="text-stone-500">الموظفون</span><span className="font-bold dark:text-white">{d.totalEmployees}</span></div><div className="flex justify-between"><span className="text-stone-500">إجازات معلقة</span><span className="font-bold dark:text-white">{d.pendingLeaveRequests}</span></div><div className="flex justify-between"><span className="text-stone-500">مهام معلقة</span><span className="font-bold dark:text-white">{d.pendingTasks}</span></div></div></Card><Card className="rounded-2xl border p-6 dark:border-stone-700"><h3 className="font-black text-stone-800 dark:text-white mb-3">ملخص مالي</h3><div className="space-y-2 text-sm"><div className="flex justify-between"><span className="text-stone-500">العملاء</span><span className="font-bold dark:text-white">{d.totalClients}</span></div><div className="flex justify-between"><span className="text-stone-500">المشاريع</span><span className="font-bold dark:text-white">{d.activeProjects}</span></div><div className="flex justify-between"><span className="text-stone-500">الإيرادات</span><span className="font-bold dark:text-white">{KWD(d.totalRevenue)}</span></div></div></Card></div></div>)
}

// ═══ SETTINGS ═══
function SettingsView() {
  const { data: governorates } = useQuery({ queryKey: ['s-gov'], queryFn: async () => { const r = await fetch('/api/governorates'); if (!r.ok) return []; const j = await r.json(); return j.data || [] } })
  const { data: departments } = useQuery({ queryKey: ['s-dept'], queryFn: async () => { const r = await fetch('/api/departments?withJobs=true'); if (!r.ok) return []; const j = await r.json(); return j.data || [] } })
  const { data: accounts } = useQuery({ queryKey: ['s-acc'], queryFn: async () => { const r = await fetch('/api/accounts'); if (!r.ok) return []; const j = await r.json(); return j.data || [] } })
  return (<div className="space-y-6"><h1 className="text-2xl font-black text-stone-800 dark:text-white">الإعدادات</h1><Card className="rounded-2xl border p-6 dark:border-stone-700"><h3 className="font-black text-stone-800 dark:text-white mb-3">القوائم المرجعية الكويتية</h3><div className="grid grid-cols-1 md:grid-cols-3 gap-4"><div><p className="text-xs font-bold text-stone-500 mb-2">المحافظات ({governorates?.length || 0})</p><div className="flex flex-wrap gap-1">{(governorates || []).map((g: any) => <Badge key={g.id} className="bg-blue-50 text-blue-600">{g.name}</Badge>)}</div></div><div><p className="text-xs font-bold text-stone-500 mb-2">الأقسام ({departments?.length || 0})</p><div className="flex flex-wrap gap-1">{(departments || []).map((d: any) => <Badge key={d.id} className="bg-emerald-50 text-emerald-600">{d.name}</Badge>)}</div></div><div><p className="text-xs font-bold text-stone-500 mb-2">الحسابات ({accounts?.length || 0})</p><div className="flex flex-wrap gap-1">{(accounts || []).slice(0, 10).map((a: any) => <Badge key={a.id} className="bg-orange-50 text-[#F5820D]">{a.code}</Badge>)}{accounts?.length > 10 && <Badge className="bg-stone-100 text-stone-500">+{accounts.length - 10}</Badge>}</div></div></div></Card><Card className="rounded-2xl border p-6 dark:border-stone-700"><h3 className="font-black text-stone-800 dark:text-white mb-3">معلومات النظام</h3><div className="space-y-2 text-sm"><div className="flex justify-between"><span className="text-stone-500">الإصدار</span><span className="font-bold dark:text-white">Nova ERP v1.0 (Prisma)</span></div><div className="flex justify-between"><span className="text-stone-500">قاعدة البيانات</span><span className="font-bold dark:text-white">SQLite + Prisma ORM</span></div><div className="flex justify-between"><span className="text-stone-500">المصادقة</span><span className="font-bold dark:text-white">NextAuth (JWT)</span></div><div className="flex justify-between"><span className="text-stone-500">الذكاء الاصطناعي</span><span className="font-bold dark:text-white">z-ai-web-dev-sdk</span></div></div></Card></div>)
}
